# # Use official NGINX image
# FROM nginx:alpine

# # Copy custom static files into the NGINX html directory
# COPY html/ /usr/share/nginx/html/

# # Expose HTTP port
# EXPOSE 80

# # Run NGINX in foreground
# CMD ["nginx", "-g", "daemon off;"]


# FROM nginx:alpine

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY html/ /usr/share/nginx/html/
# COPY ssl/ /etc/nginx/ssl/

# EXPOSE 80 443

# CMD ["nginx", "-g", "daemon off;"]



FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/
COPY ssl/ /etc/nginx/ssl/

# --- 新增下面这两行修复权限 ---
# 确保所有目录有执行权限(x)，所有文件有读取权限(r)
RUN chmod -R 755 /usr/share/nginx/html && \
    chmod -R 755 /etc/nginx/ssl/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]


